### PR TITLE
 Reworked regex to require port number and added additional tests

### PR DESCRIPTION
**Pull request by saenglert**
In response to #488 I adjusted the regex in `parseEntrypointUrl` and added new test cases for this kind of problem.

### CODE REVIEW

**Comment by erossignon** [comment]
@saenglert  we are almost here.. can you check why tests are failing ?

**Comment by saenglert** [comment]
According to appveyor:
- Certificat issues: https://ci.appveyor.com/project/erossignon/node-opcua/build/1.0.1159/job/pv9cq4329629rfq1#L3715
- Certificat issues: https://ci.appveyor.com/project/erossignon/node-opcua/build/1.0.1159/job/pv9cq4329629rfq1#L3719
- Missing or invalid client nonce https://ci.appveyor.com/project/erossignon/node-opcua/build/1.0.1159/job/pv9cq4329629rfq1#L3730
- Correctly throws an error thats not handled by `should.throwError` https://ci.appveyor.com/project/erossignon/node-opcua/build/1.0.1159/job/pv9cq4329629rfq1#L4275
- Function not found https://ci.appveyor.com/project/erossignon/node-opcua/build/1.0.1159/job/pv9cq4329629rfq1#L4304
- Error not handled by `should.throwError` https://ci.appveyor.com/project/erossignon/node-opcua/build/1.0.1159/job/pv9cq4329629rfq1#L5121
- Correct error not handled https://ci.appveyor.com/project/erossignon/node-opcua/build/1.0.1159/job/pv9cq4329629rfq1#L5452

According to travis:
- Lots of openssl errors https://travis-ci.org/node-opcua/node-opcua/jobs/387689621#L2355
- Correct error thrown but not handled https://travis-ci.org/node-opcua/node-opcua/jobs/387689621#L3138
- Different `secureChannelId` https://travis-ci.org/node-opcua/node-opcua/jobs/387689621#L3974
- Certificat error https://travis-ci.org/node-opcua/node-opcua/jobs/387689621#L4354
- Correct error not handled https://travis-ci.org/node-opcua/node-opcua/jobs/387689621#L4913
- Function not found https://travis-ci.org/node-opcua/node-opcua/jobs/387689621#L4942
- Correct error not handled https://travis-ci.org/node-opcua/node-opcua/jobs/387689621#L5765
- Correct error not handled https://travis-ci.org/node-opcua/node-opcua/jobs/387689621#L6088

Overall the errors don't seem to be raised by parts of the tests/code that I touched, so no idea why this build fails all of a sudden.

**Comment by erossignon** [comment]
i am tlaking about this test : testing ClientTCP_transport

should returns an error if url has invalid port:

**Comment by saenglert** [comment]
Sorry for the late reply, been a busy week.

Anyways here's the fix: The problem came down to `node-opcua-transport/src/tools.js:144:16` not being wrapped in a `try/catch` blocked which had the consequence of releasing the error "into the wild" instead of handling it through the callback function.

- `try/catch` added
- appropriate test case added

**Comment by erossignon** [comment]
Hi @saenglert , shall we close this PR now ? I suspect that any remaining issue have been fixed in Version2.0.0-alpha now , can you confirm ?

**Pull request closed without merging**
