### PR TITLE
fix issue #1215

### PR DESCRIPTION
**Pull request by basyskom-kraemer**
Hi!

I spend a little time and try to fix the issue #1215.

The problem is, that the "indexOf" on line 188 in "ua_multistate_value_discrete_impl.ts" returns a zero by UInt64 datatype.
I delete the "=" and now it works fine.  :-)

Best regards from Germany
Andreas (basyskom GmbH)

### CODE REVIEW

**Comment by erossignon** [comment]
Thank you, 
Can you provide the associated  unit test  ?

**Comment by basyskom-kraemer** [comment]
Hi!
Sorry for the question. But I don't understand, what you mean with unit test?
I only change the "=" in code, test it under Windows and Ubuntu with Node 14.x and 16.x on my local PC and everything works fine... Can you please tell me the steps I have to do? Thank you. :-)

**Comment by AndreasHeine** [comment]
just a test that it does not return zero anymore ;)
a test what it should not return (expect to fail) and a test what it should return (expect to pass)

**Comment by erossignon** [comment]
> Hi! Sorry for the question. But I don't understand, what you mean with unit test? I only change the "=" in code, test it under Windows and Ubuntu with Node 14.x and 16.x on my local PC and everything works fine... Can you please tell me the steps I have to do? Thank you. :-)

A bug fix  requires a non-regression test in order to be accepted.

- you need to provide a unit test with your code that demonstrates that your fix ( how small it could be) actually fixes the bug.
- the test you provide should faild if the fix is not present and should pass when the fix is present.
- you can look at the test forlder of the modules folder to see how unit test can be written.

**Comment by erossignon** [comment]
superceeded by #1252 , closing

**Pull request closed without merging**
