### PR TITLE
Added readAggregateValue support

### PR DESCRIPTION
**Pull request by shreeramk**

### CODE REVIEW

**Comment by shreeramk** [comment]
@erossignon I have made changes for reading aggregate values, can you take a look? Also, can you guide me on how to write unit test case for this.

**Comment by shreeramk** [comment]
@erossignon could you rebase the changes? All checks are failing.

**Comment by erossignon** [comment]
@shreeramk ,
I think that you resync the two history the otherway wrong.
It would have been easier to rebase your work on top of master.

Here is how I fixed your history 

````
$git log --format="%an %h %s"

tienne Rossignon 15d08d7a  improve handling of  arrayDimensions in crawler
Etienne cbca956c Update ISSUE_TEMPLATE.md
Etienne Rossignon becfcbe5 v2.6.0-alpha.1
...
Etienne Rossignon 73c4e35c handle InList in WhereClause
Shreeram Kushwaha d1e37ea0 Added readAggregateValue support
Etienne Rossignon 2b36127f v2.5.11

git reset --hard  d1e37ea0 git clean  -f  
git remote add node-opcua https://github.com/node-opcua/node-opcua
git rebase node-opcua/master
fix conflct in package.json  adding node-opcua-aggregate with the correct verisongit add .
git rebase --continue
git checkout -b readAggregate
git push
````

I have created a dedicated branch in the node-opcua where you could add the tests

**Comment by erossignon** [comment]
HI @shreeramk , if it is OK with you , I will close this PR. 
I have incorporated your change in to #792  and added the required unit tests to proof good behavior and prevent regression in the future.
Your original commit will still  appear in the history and makes you an contributor of node-opcua !

**Comment by shreeramk** [comment]
Sure. Thanks a lot @erossignon

**Comment by erossignon** [comment]
@shreeramk  enjoy your work inside node-opcua@2.6.1 ! 
Let me know if everything works as expected.

**Comment by shreeramk** [comment]
@erossignon I am getting following error while I am trying to call readAggregateValue. With the code that I had pushed, it was working fine.

NodeIds
[
  'ns=3;s=\\\\windows10\\Max_Min__PHASE_CURENT.HDA.osi pi hda',
  'ns=3;s=\\\\windows10\\Min_PHASE_CURENT.HDA.osi pi hda'
]

Error Log:
[
 HistoryReadResult {
    statusCode: ConstantStatusCode {
      _value: 2150825984,
      _description: 'The syntax of the node id is not valid.',
      _name: 'BadNodeIdInvalid'
    },
    continuationPoint: null,
    historyData: null
  },
  HistoryReadResult {
    statusCode: ConstantStatusCode {
      _value: 2150825984,
      _description: 'The syntax of the node id is not valid.',
      _name: 'BadNodeIdInvalid'
    },
    continuationPoint: null,
    historyData: null
  }
]

**Comment by erossignon** [comment]
strange ... 
can you try with resolveNodeId("ns=3;s=\\\\windows10\\Max_Min__PHASE_CURENT.HDA.osi pi hda");

**Comment by shreeramk** [comment]
Tried with resolveNodeId - still getting same error.

Also attaching screenshot from UAExpert.
Screenshot 2020-06-03 at 11 17 43 PM

**Pull request closed without merging**
