### PR TITLE
Added support for aggregate of more than one nodeId

### PR DESCRIPTION
**Pull request by shreeramk**

### CODE REVIEW

**Comment by shreeramk** [comment]
@erossignon can you pls review the changes?

**Comment by erossignon** [comment]
Thank you @shreeramk.
We need to have a extra unit test being added into packages\node-opcua-end2end-test\test\end_to_end\test_readAggregateValue.ts .
Can you provide one ?

**Comment by shreeramk** [comment]
@erossignon sure, I will add the extra unit test.

**Comment by erossignon** [comment]
Thank you, I see that the test failed. My investigation shows that it comes from an existing bug in the server side.
I can fix it if you need ... you will have to rebase your branch.

let me know.

**Comment by erossignon** [comment]
@shreeramk , I have added the fix that will make your test passe

In order to integrate them to your pull request you'll need to rebase your branch with the official node-opcua master branch

Here are the steps to do this from the command line

```bash
$ git remote add upstream https://github.com/node-opcua/node-opcua.git
$ git fetch upstream master
$ git checkout master
$ git rebase upstream/master
$ git log
```

you should get something like:
image


Then 
$ git push

**Comment by shreeramk** [comment]
> Thank you, I see that the test failed. My investigation shows that it comes from an existing bug in the server side.
> I can fix it if you need ... you will have to rebase your branch.
> 
> let me know.

Sure.

**Comment by erossignon** [comment]
@shreeramk , In fact I managed to do it on my side. I was able to rebase the PR ...  you do no need to do anything ... Tests are now running again

**Comment by shreeramk** [comment]
@erossignon great!!

**Pull request merged**
